name: Backport

# A composite action that allows Backporting via GitHub Actions (e.g. to be driven based on labels etc)

inputs:
  GITHUB_TOKEN:
    required: true
  TARGET_BRANCH:
    description: The branch in the repository to backport changes into
    required: true
  REF_TO_BACKPORT:
    description: The reference of the commit to be backported
    required: true
  BACKPORT_OPTIONS:
    description: Additional options to pass through to the tool
    required: false

runs:
  using: composite
  steps:
    - name: Get source PR number
      shell: bash
      run: |
        if [ -n "${{ github.event.number }}" ]; then
          # pull request events include the source PR number
          echo "SOURCE_PR_NUMBER=${{ github.event.number }}" >> ${GITHUB_ENV}
        else
          # push events do not so must find the PR associated with the commit
          echo "SOURCE_PR_NUMBER=$(gh api repos/${{ github.repository }}/commits/${{ github.sha }}/pulls --jq '.[0].number')" >> ${GITHUB_ENV}
        fi
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Assert branch exists
      id: assert-branch-exists
      shell: bash
      run: |
        if git ls-remote --exit-code --heads origin "${{ inputs.TARGET_BRANCH }}"; then
          echo "::debug::Branch ${{ inputs.TARGET_BRANCH }} exists"
        else
          echo "::error::Branch ${{ inputs.TARGET_BRANCH }} does not exist"
          gh pr comment "${SOURCE_PR_NUMBER}" \
            --repo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
            --body "❌ The backport branch \`${{ inputs.TARGET_BRANCH }}\` doesn't exist."
          echo "failure-already-reported=true" >> ${GITHUB_OUTPUT}
          exit 1
        fi
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Backport
      shell: bash
      run: |
        # Git metadata is required but not available out-of-the-box, inherit from the action
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        # Add "upstream" remote as checkout action doesn't include by default
        git remote add upstream "${{ github.event.repository.clone_url }}"
        git fetch --all

        backport_target_branch=upstream/"${{ inputs.TARGET_BRANCH }}"
        echo "::debug::Running backport script to backport "${{ inputs.REF_TO_BACKPORT }}" into \"${backport_target_branch}\""

        ${GITHUB_ACTION_PATH}/../../../backport \
          "${{ inputs.REF_TO_BACKPORT }}" \
          "${backport_target_branch}" \
          --non-interactive \
          ${{ inputs.BACKPORT_OPTIONS }}
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Report success
      shell: bash
      run: |
        gh pr comment "${SOURCE_PR_NUMBER}" \
          --repo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --body "👍 Created $(gh pr view --json url --jq .url) to backport into [\`${{ inputs.TARGET_BRANCH }}\`](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/tree/${{ inputs.TARGET_BRANCH }})."
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Report errors
      shell: bash
      if: failure() && steps.assert-branch-exists.outputs.failure-already-reported != 'true'
      run: |
        echo ":error::Error running action"
        echo "::group::Troubleshooting Information:"
        echo "- Repositories' GitHub action configuration - ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/settings/actions"
        echo "- Action does not run when triggered from a forked repo's PR?"
        echo "    Enable \"Run workflows from fork pull requests\""
        echo "- Backport fails with \"GraphQL: GitHub Actions is not permitted to create or approve pull requests (createPullRequest)\"?"
        echo "    Either:"
        echo "        * Enable \"Allow GitHub Actions to create and approve pull requests\""
        echo "        * Use a different \"GITHUB_TOKEN\" with appropriate permissions"
        echo "- \"GraphQL: Resource not accessible by integration (addComment)\"?"
        echo "    Either:"
        echo "        * Enable \"Send write tokens to workflows from fork pull requests\""
        echo "        * Use a different \"GITHUB_TOKEN\" with appropriate permissions"
        echo "::endgroup::"
        gh pr comment "${SOURCE_PR_NUMBER}" \
          --repo ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY} \
          --body "❌ [Failed to backport](${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}), change must be manually backported."
      env:
        GH_TOKEN: ${{ inputs.GITHUB_TOKEN }}
